name: findmyfriend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0  # Asegúrate de que esta sea la última versión disponible
  cloud_firestore: ^5.0.0  # Agregado para Firebase Firestore
  firebase_auth: ^5.0.0   # Agregado para Firebase Auth
  flutter_map: ^5.0.0 # Agregado desde el otro proyecto

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logoupt.png
    - assets/logounjbg.png
    - assets/plazavea.png
    - assets/metro.png
    - assets/tottus.png
    - assets/saga.png
    - assets/ripley.png
    - assets/marker.png
